defaultCiPipeline {
	operatingSystem = ['ubuntu']
	instanceSize = 'medium'

	environment = 'javascript'

	packageId = 'bridge-reporting'

	publisher = 'docker'
	dockerImageName = 'symbolplatform/bridge-reporting'

	codeCoverageTool = 'c8'
	minimumCodeCoverage = 95
}
