export { default as pageConfig } from './pages';

export const config = {
    SYMBOL_STATISTIC_SERVICE_URL: process.env.NEXT_PUBLIC_SYMBOL_STATISTIC_SERVICE_URL,
    SYMBOL_NODE_URL: process.env.NEXT_PUBLIC_SYMBOL_NODE_URL,
    SYMBOL_NETWORK_IDENTIFIER: process.env.NEXT_PUBLIC_SYMBOL_NETWORK_IDENTIFIER,
    SYMBOL_EPOCH_ADJUSTMENT: process.env.NEXT_PUBLIC_SYMBOL_EPOCH_ADJUSTMENT,
}
