defaultCiPipeline {
	platform = ['ubuntu']
	ciBuildDockerfile = 'javascript.Dockerfile'

	packageId = 'nem-faucet-frontend'

	publisher = 'docker'
	dockerImageName = 'symbolplatform/nem-faucet-frontend'

	codeCoverageTool = 'nyc'
	minimumCodeCoverage = 95
}
