defaultCiPipeline {
	operatingSystem = ['ubuntu']
	instanceSize = 'medium'

	environment = 'python'
	otherEnvironments = ['python-ubuntu-base', 'python-ubuntu-latest']

	packageId = 'tools-shoestring'

	publisher = 'pypi'

	codeCoverageTool = 'coverage'
	minimumCodeCoverage = 95
}
