# Setting coverage targets per flag
# Each project represent a package which has one flag
coverage:
  status:
    project:
      default:
        target: 95%  # overall project / repo coverage

      optin-puller:
        target: auto
        threshold: 1%
        flags:
          - optin-puller

      optin-reporting:
        target: auto
        threshold: 1%
        flags:
          - optin-reporting

      tools-vanity:
        target: auto
        threshold: 1%
        flags:
          - tools-vanity

# New root YAML section = `flags:`
# This is where you would define every flag from your
# uploader, and update when new Flags added
# Each flag is used to represent each package in the
# monorepo.  This allows code coverage per package.

flags:
  optin-puller:
    paths:
      - optin/puller
    carryforward: true

  optin-reporting:
    paths:
      - optin/reporting
    carryforward: true

  tools-vanity:
    paths:
      - tools/vanity
    carryforward: true
