defaultCiPipeline {
	operatingSystem = ['ubuntu']
	instanceSize = 'medium'

	ciBuildDockerfile = 'python.Dockerfile'

	packageId = 'explorer-nodewatch'

	codeCoverageTool = 'coverage'
	minimumCodeCoverage = 95
}
