defaultCiPipeline {
	operatingSystem = ['ubuntu']
	instanceSize = 'medium'

	environment = 'javascript'

	packageId = 'explorer-frontend'

	publisher = 'docker'
	dockerImageName = 'symbolplatform/explorer-frontend'

	codeCoverageTool = 'c8'
	minimumCodeCoverage = 95
}
