language: python

python:
  - 3.7

cache: pip

install:
  - pip install -r lint_requirements.txt
  - pip install -r requirements.txt

jobs:
  include:
    - stage: lint
      script:
        - sh ./lint.sh
