
export const TransportValidationResult = {
	UNSUPPORTED_CHAIN: 'UNSUPPORTED_CHAIN',
	INACTIVE_CHAIN: 'INACTIVE_CHAIN',
	NETWORK_MISMATCH: 'NETWORK_MISMATCH',
	CHAIN_ID_MISMATCH: 'CHAIN_ID_MISMATCH'
};
