language: python

python:
  - 3.7

env:
  global:
    RELEASE_BRANCH=main

cache: pip

install:
  - pip install -r lint_requirements.txt
  - pip install -r requirements.txt

jobs:
  include:
    - stage: lint
      script:
        - sh ./lint.sh

    - stage: run account scripts
      script:
        - python -m account.symbol_multisig_create --input account/samples/symbol_multisig_create.yaml
        - python -m account.two_part_send --input account/samples/two_part_send.yaml
        - python -m account.verify_ownership --input account/samples/verify_ownership.yaml

    - stage: run health scripts
      script:
        - python -m health.check_nem_balances --resources templates/nem.mainnet.yaml --groups core
        - python -m health.check_nem_balances --resources templates/symbol.mainnet.yaml --groups core

    - stage: run history scripts (nem)
      if: branch = env(RELEASE_BRANCH)
      script:
        - python -m history.downloader --input templates/nem.mainnet.yaml --start-date 2021-08-01 --end-date 2021-08-31 --output _histout/raw
        - mkdir -p _histout/all
        - python -m history.merger --input _histout/raw --output _histout/all/full.csv --ticker nem
        - mkdir -p _histout/account
        - python -m history.grouper --input _histout/all/full.csv --output _histout/account/grouped.csv --mode account
        - python -m history.summarizer --input _histout/account --output _histout/balances.csv --mode account
        # not: reconciler will fail when there is only a partial download
        - python -m history.reconciler --input _histout/balances.csv --resources templates/nem.mainnet.yaml --mode spot || test $? -eq 1

    - stage: run history scripts (symbol)
      if: branch = env(RELEASE_BRANCH)
      script:
        - python -m history.downloader --input templates/symbol.mainnet.yaml --start-date 2021-08-01 --end-date 2021-08-31 --output _histout/raw
        - mkdir -p _histout/all
        - python -m history.merger --input _histout/raw --output _histout/all/full.csv --ticker symbol
        - mkdir -p _histout/account
        - python -m history.grouper --input _histout/all/full.csv --output _histout/account/grouped.csv --mode account
        - python -m history.summarizer --input _histout/account --output _histout/balances.csv --mode account
        # not: reconciler will fail when there is only a partial download
        - python -m history.reconciler --input _histout/balances.csv --resources templates/symbol.mainnet.yaml --mode spot || test $? -eq 3

    - stage: run network scripts
      script:
        - python -m network.richlist_symbol --resources templates/symbol.mainnet.yaml --min-balance 50000000 --output 50M.csv
        - python -m network.harvester --resources templates/nem.mainnet.yaml --days 0.01 --output nem_harvesters.csv
        - python -m network.harvester --resources templates/symbol.mainnet.yaml --days 0.01 --output symbol_harvesters.csv

    - stage: run network scripts (crawl)
      script:
        - python -m network.nodes --resources templates/nem.mainnet.yaml --timeout 1 --output nemnodes.json
