language: python

python:
  - 3.7

cache: pip

install:
  - pip install -r lint_requirements.txt
  - pip install -r requirements.txt

jobs:
  include:
    - stage: lint
      script:
        - isort --check-only --line-length 140 core health history scripts
        - pycodestyle --config=.pycodestyle -- core health history scripts
        - pylint --load-plugins pylint_quotes -- core health history scripts

  include:
    - stage: run scripts
      script:
        - python -m scripts.verify_account_ownership --input scripts/samples/verify_account_ownership.yaml
        - python -m scripts.two_part_send --input scripts/samples/two_part_send.yaml
