defaultCiPipeline {
	operatingSystem = ['ubuntu']
	instanceSize = 'medium'

	ciBuildDockerfile = 'javascript.Dockerfile'

	packageId = 'faucet-authenticator'

	publisher = 'docker'
	dockerImageName = 'symbolplatform/faucet-authenticator'

	codeCoverageTool = 'c8'
	minimumCodeCoverage = 95
}
