const config = {
	NATIVE_MOSAIC_ID: process.env.NEXT_PUBLIC_NATIVE_MOSAIC_ID,
	NATIVE_MOSAIC_TICKER: process.env.NEXT_PUBLIC_NATIVE_MOSAIC_TICKER,
	NATIVE_MOSAIC_DIVISIBILITY: +process.env.NEXT_PUBLIC_NATIVE_MOSAIC_DIVISIBILITY,
	BLOCKCHAIN_UNWIND_LIMIT: +process.env.NEXT_PUBLIC_BLOCKCHAIN_UNWIND_LIMIT,
	API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL
};

export default config;
