const publicAppConfig = {
	NATIVE_MOSAIC_ID: process.env.NATIVE_MOSAIC_ID,
	NATIVE_MOSAIC_TICKER: process.env.NATIVE_MOSAIC_TICKER,
	NATIVE_MOSAIC_DIVISIBILITY: +process.env.NATIVE_MOSAIC_DIVISIBILITY,
	BLOCKCHAIN_UNWIND_LIMIT: +process.env.BLOCKCHAIN_UNWIND_LIMIT,
	REQUEST_TIMEOUT: +process.env.REQUEST_TIMEOUT,
	API_BASE_URL: process.env.API_BASE_URL,
	SUPERNODE_API_URL: process.env.SUPERNODE_API_URL,
	NODELIST_URL: process.env.NODELIST_URL,
	MARKET_DATA_URL: process.env.MARKET_DATA_URL,
	HISTORICAL_PRICE_URL: process.env.HISTORICAL_PRICE_URL,
	SOCIAL_URL_TWITTER: process.env.SOCIAL_URL_TWITTER,
	SOCIAL_URL_GITHUB: process.env.SOCIAL_URL_GITHUB,
	SOCIAL_URL_DISCORD: process.env.SOCIAL_URL_DISCORD,
	FOOTER_URL_DOCS: process.env.FOOTER_URL_DOCS,
	FOOTER_URL_TECHNICAL_REFERENCE: process.env.FOOTER_URL_TECHNICAL_REFERENCE,
	FOOTER_URL_FAUCET: process.env.FOOTER_URL_FAUCET,
	FOOTER_URL_SUPERNODE_PROGRAM: process.env.FOOTER_URL_SUPERNODE_PROGRAM
};

const isClientSide = typeof window !== 'undefined';

export default isClientSide ? window.appConfig : publicAppConfig;
