const config = {
	PLATFORM: process.env.NEXT_PUBLIC_PLATFORM,
	API_BASE_URL: process.env.NEXT_PUBLIC_API_BASE_URL,
	NATIVE_MOSAIC_ID: process.env.NEXT_PUBLIC_NATIVE_MOSAIC_ID,
	NATIVE_MOSAIC_TICKER: process.env.NEXT_PUBLIC_NATIVE_MOSAIC_TICKER,
	NATIVE_MOSAIC_DIVISIBILITY: +process.env.NEXT_PUBLIC_NATIVE_MOSAIC_DIVISIBILITY,
	REQUEST_TIMEOUT: +process.env.NEXT_PUBLIC_REQUEST_TIMEOUT,
	SOCIAL_URL_TWITTER: process.env.NEXT_PUBLIC_SOCIAL_URL_TWITTER,
	SOCIAL_URL_GITHUB: process.env.NEXT_PUBLIC_SOCIAL_URL_GITHUB,
	SOCIAL_URL_DISCORD: process.env.NEXT_PUBLIC_SOCIAL_URL_DISCORD,
	FOOTER_URL_DOCS: process.env.NEXT_PUBLIC_FOOTER_URL_DOCS,
	FOOTER_URL_TECHNICAL_REFERENCE: process.env.NEXT_PUBLIC_FOOTER_URL_TECHNICAL_REFERENCE,
	FOOTER_URL_FAUCET: process.env.NEXT_PUBLIC_FOOTER_URL_FAUCET,
	FOOTER_URL_SUPERNODE_PROGRAM: process.env.NEXT_PUBLIC_FOOTER_URL_SUPERNODE_PROGRAM
};

export default {
	...config,
	...require(`@/_variants/${config.PLATFORM}/config`).config,
};
