defaultCiPipeline {
	operatingSystem = ['ubuntu']
	instanceSize = 'medium'

	ciBuildDockerfile = 'postgres.Dockerfile'

	packageId = 'explorer-rest'

	codeCoverageTool = 'coverage'
	minimumCodeCoverage = 95

	discordWebHookUrlId = 'EXPLORER_DISCORD_WEB_HOOK_URL_ID'
}
