defaultCiPipeline {
	platform = ['ubuntu']
	ciBuildDockerfile = 'javascript.Dockerfile'

	packageId = 'optin-reporting'

	publisher = 'docker'
	dockerImageName = 'symbolplatform/optin-reporting'

	codeCoverageTool = 'nyc'
	minimumCodeCoverage = 95
}
