export { default as pageConfig } from './pages';

export const config = {
	NEM_BLOCKCHAIN_UNWIND_LIMIT: +process.env.NEXT_PUBLIC_NEM_BLOCKCHAIN_UNWIND_LIMIT,
	NEM_SUPERNODE_API_URL: process.env.NEXT_PUBLIC_NEM_SUPERNODE_API_URL,
	NEM_NODELIST_URL: process.env.NEXT_PUBLIC_NEM_NODELIST_URL,
    NEM_MARKET_DATA_URL: process.env.NEXT_PUBLIC_NEM_MARKET_DATA_URL,
    NEM_HISTORICAL_PRICE_URL: process.env.NEXT_PUBLIC_NEM_HISTORICAL_PRICE_URL,
}
