defaultCiPipeline {
	operatingSystem = ['ubuntu']
	instanceSize = 'medium'

	ciBuildDockerfile = 'javascript.Dockerfile'

	packageId = 'snap-backend'

	publisher = 'docker'
	dockerImageName = 'symbolplatform/snap-backend'

	codeCoverageTool = 'nyc'
	minimumCodeCoverage = 95
}
