defaultCiPipeline {
	operatingSystem = ['ubuntu']
	instanceSize = 'medium'

	ciBuildDockerfile = 'javascript.Dockerfile'

	packageId = 'faucet-backend'

	publisher = 'docker'
	dockerImageName = 'symbolplatform/faucet-backend'

	codeCoverageTool = 'c8'
	minimumCodeCoverage = 95

	discordWebHookUrlId = 'WALLET_DISCORD_WEB_HOOK_URL_ID'
}
