defaultCiPipeline {
	operatingSystem = ['ubuntu']
	instanceSize = 'medium'

	ciBuildDockerfile = 'python.Dockerfile'

	packageId = 'lightapi-python'

	publisher = 'pypi'

	codeCoverageTool = 'coverage'
	minimumCodeCoverage = 95

	discordWebHookUrlId = 'SDK_DISCORD_WEB_HOOK_URL_ID'
}
