defaultCiPipeline {
	operatingSystem = ['ubuntu']
	instanceSize = 'medium'

	ciBuildDockerfile = 'python.Dockerfile'

	packageId = 'lightapi-python'

	publisher = 'pypi'

	codeCoverageTool = 'coverage'
	minimumCodeCoverage = 95
}
